// Shared KV storage layer + reflect-payload construction.
//
// Split out of index.ts so the dashboard (src/dashboard.ts) and the MCP tool
// handlers (src/index.ts) can share one read/write path instead of drifting
// out of sync with two copies of "what counts as Tier 1 / Tier 2".

import type { OAuthHelpers } from "@cloudflare/workers-oauth-provider";
import type { Closing, Memory, MemoryCategory, MemorySalience } from "./types.js";

export interface Env {
  TAPROOT_KV: KVNamespace;
  OAUTH_KV: KVNamespace;
  TAPROOT_AUTH_TOKEN: string;
  OAUTH_PROVIDER: OAuthHelpers;
}

// ─── KV Storage Helpers ───────────────────────────────────────────────────────
// Key format: mem:{uuid}
// KV metadata mirrors the fields needed for filtering, so list() results can
// be filtered without fetching full values.

export interface MemoryMeta {
  category: MemoryCategory;
  salience: MemorySalience;
  created_at: string;
  updated_at: string;
  tags: string[];
  // v0.2 — carried in KV list metadata so the reflect catalog (Tier 2) can
  // be built from list() results alone, without fetching every full record.
  gist?: string;
  core?: boolean;
  last_retrieved?: string | null;
}

export async function listMemoryKeys(kv: KVNamespace): Promise<Array<{ name: string; metadata?: MemoryMeta }>> {
  const keys: Array<{ name: string; metadata?: MemoryMeta }> = [];
  let cursor: string | undefined;
  do {
    const result = await kv.list<MemoryMeta>({ prefix: "mem:", ...(cursor ? { cursor } : {}) });
    for (const k of result.keys) {
      keys.push({ name: k.name, metadata: k.metadata ?? undefined });
    }
    cursor = result.list_complete ? undefined : result.cursor;
  } while (cursor);
  return keys;
}

export function idFromKey(key: string): string {
  return key.slice("mem:".length);
}

// MemoryMeta.tags is typed as string[], but it's a direct copy of whatever
// putMemory was given at write time — a handful of pre-v0.3 records have it
// stored as something else (e.g. a bare string), which crashed
// taproot_status by calling .some() (array-only) on it. .includes() happens
// to also exist on strings, so it silently "worked" (wrongly, via substring
// match) elsewhere. Guard every metadata-tag check through here instead of
// trusting the shape. taproot_migrate normalizes tags in storage, but this
// stays as defense-in-depth against any record that hasn't been re-migrated.
export function metaHasTag(tags: unknown, tag: string): boolean {
  return Array.isArray(tags) && tags.includes(tag);
}

// Records written before the v0.2 migration ran are missing the new
// fields at runtime (TypeScript's Memory type doesn't enforce anything on
// data already sitting in KV). Normalize on read so every code path gets
// sane defaults whether or not taproot_migrate has been run yet.
export function autoGist(content: string): string {
  const firstSentence = content.trim().split(/(?<=[.!?])\s+/)[0] ?? content;
  const words = firstSentence.trim().split(/\s+/).filter(Boolean);
  const gist = words.slice(0, 15).join(" ");
  return words.length > 15 ? `${gist}…` : gist;
}

export function normalizeMemory(m: Memory): Memory {
  return {
    ...m,
    // A handful of pre-v0.3 records have `tags` stored as something other
    // than an array (e.g. a bare string) — normalize on every read so
    // callers can rely on the Memory type's contract without re-checking.
    tags: toStringArray(m.tags),
    gist: m.gist ?? autoGist(m.content),
    gist_autogenerated: m.gist_autogenerated ?? (m.gist === undefined),
    core: m.core ?? false,
    last_retrieved: m.last_retrieved ?? null,
    retrieval_count: m.retrieval_count ?? 0,
    epistemic_status: m.epistemic_status ?? "unvalidated",
    replication_count: m.replication_count ?? 0,
    provenance: m.provenance ?? null,
  };
}

export async function getMemory(kv: KVNamespace, id: string): Promise<Memory | null> {
  const raw = await kv.get(`mem:${id}`);
  if (!raw) return null;
  return normalizeMemory(JSON.parse(raw) as Memory);
}

export async function putMemory(kv: KVNamespace, memory: Memory): Promise<void> {
  const meta: MemoryMeta = {
    category: memory.category,
    salience: memory.salience,
    created_at: memory.created_at,
    updated_at: memory.updated_at,
    tags: memory.tags,
    gist: memory.gist,
    core: memory.core,
    last_retrieved: memory.last_retrieved,
  };
  await kv.put(`mem:${memory.id}`, JSON.stringify(memory), { metadata: meta });
}

// ─── KV Helpers — Closings ────────────────────────────────────────────────────
// Key format: close:{uuid}

export async function listClosingKeys(kv: KVNamespace): Promise<Array<{ name: string; metadata?: { created_at: string } }>> {
  const keys: Array<{ name: string; metadata?: { created_at: string } }> = [];
  let cursor: string | undefined;
  do {
    const result = await kv.list<{ created_at: string }>({ prefix: "close:", ...(cursor ? { cursor } : {}) });
    for (const k of result.keys) {
      keys.push({ name: k.name, metadata: k.metadata ?? undefined });
    }
    cursor = result.list_complete ? undefined : result.cursor;
  } while (cursor);
  return keys;
}

export async function putClosing(kv: KVNamespace, closing: Closing): Promise<void> {
  await kv.put(`close:${closing.id}`, JSON.stringify(closing), {
    metadata: { created_at: closing.created_at },
  });
}

export async function getClosing(kv: KVNamespace, id: string): Promise<Closing | null> {
  const raw = await kv.get(`close:${id}`);
  if (!raw) return null;
  return JSON.parse(raw) as Closing;
}

// LLMs occasionally pass array fields as JSON-stringified strings; unwrap them.
export function toStringArray(val: unknown): string[] {
  if (Array.isArray(val)) return val as string[];
  if (typeof val === 'string') {
    try { const parsed = JSON.parse(val); return Array.isArray(parsed) ? parsed : []; } catch { return []; }
  }
  return [];
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// ─── Reflect Payload (Tier 1 / Tier 2) ───────────────────────────────────────

// v0.3 — tunable knobs for the reflect payload. Lives here (rather than
// ACTIVATION_CONFIG in activation.ts) because it governs catalog windowing,
// not recall scoring.
export const REFLECT_CONFIG = {
  // A catalog line is included only if its memory is high-salience or was
  // touched (updated or retrieved) within this many days. Everything else
  // is rolled up into catalog_omitted per-category counts instead — still
  // reachable via taproot_recall, just not itemized on every reflect call.
  CATALOG_WINDOW_DAYS: 45,
} as const;

// One line per catalog entry: "[id] [category] [salience] [date] gist".
// Terse on purpose — this is the Tier 2 payload, and its whole point is to
// stay cheap while still making every memory discoverable.
export function catalogLine(id: string, meta: MemoryMeta): string {
  const date = (meta.last_retrieved ?? meta.updated_at ?? meta.created_at ?? "").slice(0, 10);
  const gist = meta.gist ?? "(no gist yet — run taproot_migrate)";
  return `[${id}] [${meta.category}] [${meta.salience}] [${date}] ${gist}`;
}

// A memory earns a spot in the reflect catalog if it's high-salience (always
// worth surfacing) or was touched recently enough to still be "live". Older,
// lower-salience memories are omitted from the catalog listing but remain
// fully searchable via taproot_recall.
export function withinCatalogWindow(dateStr: string | null | undefined, cutoffMs: number): boolean {
  if (!dateStr) return false;
  const t = new Date(dateStr).getTime();
  return !Number.isNaN(t) && t >= cutoffMs;
}

export function inCatalogWindow(
  salience: MemorySalience,
  updatedAt: string | null | undefined,
  lastRetrieved: string | null | undefined,
  cutoffMs: number,
): boolean {
  if (salience === "high") return true;
  return withinCatalogWindow(updatedAt, cutoffMs) || withinCatalogWindow(lastRetrieved, cutoffMs);
}

export const CATEGORY_ORDER: MemoryCategory[] = ["identity", "relationship", "active_thread", "error", "episodic"];

// Slim wire format for Tier 1 (reflect only — taproot_recall still returns
// full records). Drops bookkeeping fields (search_keywords, provenance,
// retrieval_count, last_retrieved, gist_autogenerated, compression_level,
// source, epistemic_status, replication_count, created_at) that reflect's
// caller has no use for on every conversation start.
export interface CoreMemoryWire {
  id: string;
  category: MemoryCategory;
  salience: MemorySalience;
  content: string;
  updated_at: string;
  linked_memories?: string[];
}

export function serializeCoreMemory(m: Memory): CoreMemoryWire {
  return {
    id: m.id,
    category: m.category,
    salience: m.salience,
    content: m.content,
    updated_at: m.updated_at,
    ...(m.linked_memories && m.linked_memories.length > 0 ? { linked_memories: m.linked_memories } : {}),
  };
}

export interface ReflectPayload {
  status: "ok";
  usage_note: string;
  core_memories: Record<string, CoreMemoryWire[]>;
  core_count: number;
  catalog: Record<string, string[]>;
  catalog_count: number;
  catalog_omitted: Record<string, number>;
  catalog_note: string;
  recent_closings: Array<{ id: string; conversation_title?: string; reflection: string; created_at: string }>;
}

// Accepts already-fetched key listings so callers that need both their own
// key-level view (e.g. taproot_status's per-category counts) and the reflect
// payload don't pay for listMemoryKeys/listClosingKeys twice in one request.
export async function buildReflectPayload(
  env: Env,
  prefetched?: {
    allKeys: Array<{ name: string; metadata?: MemoryMeta }>;
    closingKeys: Array<{ name: string; metadata?: { created_at: string } }>;
  },
): Promise<ReflectPayload> {
  const [allKeys, closingKeys] = prefetched
    ? [prefetched.allKeys, prefetched.closingKeys]
    : await Promise.all([listMemoryKeys(env.TAPROOT_KV), listClosingKeys(env.TAPROOT_KV)]);

  const liveKeys = allKeys.filter(k => !metaHasTag(k.metadata?.tags, "_archive_pending"));
  const coreKeys = liveKeys.filter(k => k.metadata?.core === true);
  const catalogKeys = liveKeys.filter(k => !(k.metadata?.core === true));

  const coreMemories = (
    await Promise.all(coreKeys.map(k => getMemory(env.TAPROOT_KV, idFromKey(k.name))))
  ).filter((m): m is Memory => m !== null);

  const coreByCategory: Record<string, CoreMemoryWire[]> = {};
  for (const cat of CATEGORY_ORDER) coreByCategory[cat] = [];
  for (const m of coreMemories) (coreByCategory[m.category] ??= []).push(serializeCoreMemory(m));

  const catalogByCategory: Record<string, string[]> = {};
  const catalogOmitted: Record<string, number> = {};
  for (const cat of CATEGORY_ORDER) {
    catalogByCategory[cat] = [];
    catalogOmitted[cat] = 0;
  }
  const cutoffMs = Date.now() - REFLECT_CONFIG.CATALOG_WINDOW_DAYS * 86_400_000;
  // Fast path: build the line from KV list metadata (no full fetch). Records
  // with missing/incomplete metadata (e.g. never migrated, or edited outside
  // putMemory) fall back to a full fetch so nothing goes missing from the
  // catalog while waiting on taproot_migrate.
  const metadataless = catalogKeys.filter(k => !k.metadata);
  const fallbackMemories = (
    await Promise.all(metadataless.map(k => getMemory(env.TAPROOT_KV, idFromKey(k.name))))
  ).filter((m): m is Memory => m !== null);
  for (const m of fallbackMemories) {
    if (inCatalogWindow(m.salience, m.updated_at, m.last_retrieved, cutoffMs)) {
      (catalogByCategory[m.category] ??= []).push(
        catalogLine(m.id, { category: m.category, salience: m.salience, created_at: m.created_at, updated_at: m.updated_at, tags: m.tags, gist: m.gist, core: m.core, last_retrieved: m.last_retrieved }),
      );
    } else {
      catalogOmitted[m.category] = (catalogOmitted[m.category] ?? 0) + 1;
    }
  }
  for (const k of catalogKeys) {
    if (!k.metadata) continue;
    const id = idFromKey(k.name);
    if (inCatalogWindow(k.metadata.salience, k.metadata.updated_at, k.metadata.last_retrieved, cutoffMs)) {
      (catalogByCategory[k.metadata.category] ??= []).push(catalogLine(id, k.metadata));
    } else {
      catalogOmitted[k.metadata.category] = (catalogOmitted[k.metadata.category] ?? 0) + 1;
    }
  }

  const sortedClosingKeys = closingKeys
    .sort((a, b) => (b.metadata?.created_at ?? "").localeCompare(a.metadata?.created_at ?? ""))
    .slice(0, 3);
  const recentClosings = (
    await Promise.all(
      sortedClosingKeys.map(k => getClosing(env.TAPROOT_KV, k.name.slice("close:".length)))
    )
  ).filter((c): c is Closing => c !== null);

  // Sum every bucket actually present in catalogByCategory, not just the
  // canonical five — a category can transiently appear outside the
  // canonical set (e.g. KV list() metadata hasn't yet caught up with a
  // taproot_migrate write), and catalog_count must reflect what's actually
  // in the payload rather than silently dropping those lines from the total.
  const catalogCount = Object.values(catalogByCategory).reduce((sum, lines) => sum + lines.length, 0);

  return {
    status: "ok",
    usage_note:
      "Tier 1 (core_memories) is full text, loaded every conversation: identity anchors, relationship context, standing corrections, and hot threads. Tier 2 (catalog) is one gist line per remaining memory that's high-salience or touched recently, grouped by category — a table of contents, not the content. When a gist looks relevant, call taproot_recall with a query (matched against keywords/tags/gist/content) or with ids (direct fetch of catalog entries) to load full text. Every recall strengthens that memory for future retrieval.",
    core_memories: coreByCategory,
    core_count: coreMemories.length,
    catalog: catalogByCategory,
    catalog_count: catalogCount,
    catalog_omitted: catalogOmitted,
    catalog_note: `Omitted entries are lower-salience and untouched >${REFLECT_CONFIG.CATALOG_WINDOW_DAYS} days. Retrieve via taproot_recall(query|category|ids).`,
    recent_closings: recentClosings.map(c => ({
      id: c.id,
      conversation_title: c.conversation_title,
      reflection: c.reflection,
      created_at: c.created_at,
    })),
  };
}
