// Memory schema — matches the spec §5.2
// Closing schema — end-of-conversation reflections

export type MemoryCategory =
  | "identity"
  | "relationship"
  | "active_thread"
  | "episodic"
  | "error";

export type MemorySalience = "high" | "medium" | "low";

export type MemorySourceType =
  | "direct_observation"
  | "thread_summary"
  | "compression"
  | "manual_edit";

export interface MemorySource {
  type: MemorySourceType;
  conversation_id?: string;
  transcript_ref?: string;
  summary_ref?: string;
}

// Epistemic status is populated by a parallel validation project — schema
// support lands now, backfilled to "unvalidated", so we don't have to
// migrate the store a second time when that project starts writing to it.
export type EpistemicStatus =
  | "observed"
  | "inferred"
  | "replicated"
  | "contested"
  | "unvalidated";

export interface Memory {
  id: string;
  category: MemoryCategory;
  content: string;
  salience: MemorySalience;
  created_at: string;
  updated_at: string;
  source: MemorySource;
  compression_level: number;
  linked_memories: string[];
  tags: string[];
  conversation_url?: string;
  search_keywords?: string[];

  // v0.2 — dynamic recall (see DESIGN.md §5.2a)
  gist: string;
  gist_autogenerated?: boolean;
  core: boolean;
  last_retrieved: string | null;
  retrieval_count: number;

  // v0.2 — validation-project fields, populated later
  epistemic_status: EpistemicStatus;
  replication_count: number;
  provenance: string | null;
}

export interface Closing {
  id: string;
  type: "close";
  reflection: string;
  conversation_url?: string;
  conversation_title?: string;
  created_at: string;
}
